name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Or your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Or use a personal access token

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
            ${{ github.repository_owner }}/${{ github.repository }}:latest
          push: true
